---
- name: Load var file with default values based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - >-
          {{ ansible_distribution }}_{{ ansible_distribution_release }}_{{
          ansible_architecture }}.yml
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}_{{ ansible_architecture }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}_{{ ansible_architecture }}.yml"
        - "{{ ansible_os_family }}.yml"
        - Default_{{ ansible_architecture }}.yml
        - Default.yml
      paths:
        - "{{ role_path }}/vars"

- name: Add archive repositories
  when: ansible_distribution_release in supported_releases | default([])
  block:
    - name: Remove non-archive repositories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list
        - /etc/apt/sources.list.d/debian.sources

    - name: Add archive repositories (pre-Bookworm)
      when: ansible_distribution_release not in ["bookworm", "trixie"]
      ansible.builtin.apt_repository:
        filename: archive
        repo: "{{ item | format(ansible_distribution_release) }}"
        update_cache: "{{ debian_archive_update_cache }}"
      loop: "{{ source_list_entries }}"

    - name: Add archive repositories (Bookworm and later)
      when: ansible_distribution_release in ["bookworm", "trixie"]
      block:
        - name: Install a required prerequisite
          ansible.builtin.package:
            name:
              - python3-debian

        - name: Add archive repositories
          ansible.builtin.deb822_repository:
            components:
              - main
            name: archive
            signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
            suites: "{{ item.suites }}"
            uris: "{{ item.uris }}"
          loop:
            - uris:
                - http://archive.debian.org/debian
              suites:
                - "{{ ansible_distribution_release }}"
                - "{{ ansible_distribution_release }}-updates"
            - uris:
                - http://archive.debian.org/debian-security
              suites:
                - "{{ ansible_distribution_release }}/updates"
          register: add_archive_repos

        - name: Update the package cache
          ansible.builtin.apt:
            update_cache: true
          when:
            - add_archive_repos.changed
            - debian_archive_update_cache
